<?php require '__header.phtml'; ?>
<?php require '__menu.phtml'; ?>

<h1>Change Password</h1>
<?php if ($isChangeSuccess) : ?>
  <div style="color: green; margin-bottom: 2vh; font-weight: bold;">
    Change Password Successful
  </div>
<?php endif; ?>
<form action="/changePass" method="POST">
  <table>
    <tr>
      <td style="vertical-align:top; padding-top: 2px;">
        <label for="currentPass">Current Password</label>
      </td>
      <td>
        <input type="password" name="currentPass" id="currentPass" />
        <?php if ($isChangePassErrorCurrentPwd) : ?>
          <div style="color: red; margin-bottom: 2vh; font-weight: bold;">
            Password is incorrect
          </div>
        <?php endif; ?>
      </td>
    </tr>
    <tr>
      <td>
        <label for="newPass">New Password</label>
      </td>
      <td>
        <input type="password" name="newPass" id="newPass" />
      </td>
    </tr>
    <tr>
      <td style="vertical-align:top; padding-top: 2px;">
        <label for="againPass">New Password (Again)</label>
      </td>
      <td>
        <input type="password" name="againPass" id="againPass" />
        <?php if ($isChangePassErrorMatch) : ?>
          <div style="color: orange; margin-bottom: 2vh; font-weight: bold;">
            Password do not match
          </div>
        <?php endif; ?>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>
        <button type="submit">Change</button>
      </td>
    </tr>
  </table>
</form>
<?php require '__footer.phtml'; ?>